In [31]:
%matplotlib inline

In [32]:
import numpy as np

In [33]:
import matplotlib.pyplot as plt

In [34]:
import cv2

In [35]:
import os

In [36]:
cat_folder = "//Mac/Home/Downloads/catanddog/training_set/training_set/cats"

In [37]:
dog_folder = "//Mac/Home/Downloads/catanddog/training_set/training_set/dogs"

In [38]:
os.listdir(cat_folder)

['cat.2718.jpg',
 'cat.3406.jpg',
 'cat.1211.jpg',
 'cat.1577.jpg',
 'cat.952.jpg',
 'cat.3360.jpg',
 'cat.946.jpg',
 'cat.3374.jpg',
 'cat.1563.jpg',
 'cat.1205.jpg',
 'cat.3412.jpg',
 'cat.2724.jpg',
 'cat.2042.jpg',
 'cat.3348.jpg',
 'cat.2056.jpg',
 'cat.2730.jpg',
 'cat.1239.jpg',
 'cat.6.jpg',
 'cat.2903.jpg',
 'cat.749.jpg',
 'cat.991.jpg',
 'cat.985.jpg',
 'cat.2917.jpg',
 'cat.1588.jpg',
 'cat.2081.jpg',
 'cat.775.jpg',
 'cat.761.jpg',
 'cat.2095.jpg',
 'cat.588.jpg',
 'cat.3162.jpg',
 'cat.1775.jpg',
 'cat.1013.jpg',
 'cat.3604.jpg',
 'cat.3610.jpg',
 'cat.1007.jpg',
 'cat.1761.jpg',
 'cat.2268.jpg',
 'cat.3176.jpg',
 'cat.1991.jpg',
 'cat.1749.jpg',
 'cat.2240.jpg',
 'cat.3638.jpg',
 'cat.2526.jpg',
 'cat.2532.jpg',
 'cat.2254.jpg',
 'cat.1985.jpg',
 'cat.239.jpg',
 'cat.2283.jpg',
 'cat.577.jpg',
 'cat.1952.jpg',
 'cat.211.jpg',
 'cat.3823.jpg',
 'cat.205.jpg',
 'cat.3837.jpg',
 'cat.1946.jpg',
 'cat.3189.jpg',
 'cat.563.jpg',
 'cat.2297.jpg',
 'cat.3016.jpg',
 'cat.2308.jp

In [39]:
for filename in os.listdir(cat_folder):
    img_path = os.path.join(cat_folder,filename)
    print(img_path)


//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.2718.jpg
//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.3406.jpg
//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.1211.jpg
//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.1577.jpg
//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.952.jpg
//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.3360.jpg
//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.946.jpg
//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.3374.jpg
//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.1563.jpg
//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.1205.jpg
//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.3412.jpg
//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.2724.jpg
//Mac/Home/Downloads/catanddog/training_set/training_set/cats\cat.2042.jpg
//Mac/Home/Downloads/catand

In [40]:
## joining the folder together with filename
## read the image and convert it to grayscale
#resize the image
## flatten the image(1d array)
## push the flatten image into a list
## push the label into a list

In [41]:
def load_imagedate(folder,label,img_size=(65,65)):
    images = []
    labels = []
    for filename in os.listdir(folder):
        img_path = os.path.join(folder,filename)
        img = cv2.imread(img_path,cv2.IMREAD_GRAYSCALE)
        img_resize = cv2.resize(img,img_size)
        img_flattened = img_resize.flatten()
        images.append(img_flattened)
        labels.append(label)
    return images, labels
        
    

In [42]:
cat_images, cat_labels = load_imagedate(cat_folder,0)

In [43]:
dog_images, dog_labels = load_imagedate(dog_folder,1)


In [44]:
X = np.array(cat_images + dog_images)
Y = np.array(cat_labels + dog_labels)

In [45]:
X.shape

(8005, 4225)

In [46]:
Y.shape

(8005,)

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
x_train ,x_test, y_train, y_test= train_test_split(X,Y, random_state=10, test_size = 0.2) ##test size chane the default from 70/30 to 80/20

In [49]:
from sklearn.svm import SVC

In [50]:
#initializing your model
svm = SVC(random_state =20)

In [51]:
X.shape

(8005, 4225)

In [52]:
svm.fit(x_train,y_train)

SVC(random_state=20)

In [53]:
from sklearn.metrics import classification_report

In [54]:
predicted_values = svm.predict(x_test)

In [55]:
print(classification_report(y_test,predicted_values))

              precision    recall  f1-score   support

           0       0.63      0.57      0.60       813
           1       0.59      0.66      0.62       788

    accuracy                           0.61      1601
   macro avg       0.61      0.61      0.61      1601
weighted avg       0.61      0.61      0.61      1601



In [75]:
def predict_image(img_path):
    img = cv2.imread(img_path,cv2.IMREAD_GRAYSCALE)
    img_resize = cv2.resize(img,(65,65))
    img_flatten= img_resize.flatten().reshape(1,-1)
    predicted_class = svm.predict(img_flatten)
    if predicted_class == 0:
        return "CAT"
    else: return "Dog"
    return predicted_class

In [76]:
predict_image("dog.2.jpg")

'Dog'

In [77]:
predict_image("ronaldo.jpg")

'CAT'

In [78]:
load_imagedate(cat_folder,0)

([array([26, 25, 26, ..., 52, 46, 42], dtype=uint8),
  array([118, 118,  49, ...,  51,  62,  64], dtype=uint8),
  array([255, 255, 255, ...,  80,  77,  65], dtype=uint8),
  array([162, 197, 218, ..., 121, 115, 106], dtype=uint8),
  array([16,  5,  5, ..., 67, 83, 63], dtype=uint8),
  array([123,  76,  82, ...,  33,  35,  37], dtype=uint8),
  array([ 67, 179, 190, ...,  78,  73,  66], dtype=uint8),
  array([139, 164, 168, ...,  19,  17,  14], dtype=uint8),
  array([ 63,  65,  64, ..., 107, 110, 130], dtype=uint8),
  array([ 40,  43,  44, ..., 146, 140, 143], dtype=uint8),
  array([157, 156, 158, ..., 189, 185, 190], dtype=uint8),
  array([32, 23, 31, ...,  1,  4,  2], dtype=uint8),
  array([ 77, 146, 156, ..., 106, 114, 114], dtype=uint8),
  array([44, 49, 47, ..., 24, 19, 12], dtype=uint8),
  array([119, 131,  84, ..., 124, 130, 110], dtype=uint8),
  array([208, 208, 200, ...,  30,  23,  25], dtype=uint8),
  array([255, 254, 181, ..., 128, 203, 193], dtype=uint8),
  array([193, 192, 19